version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
#    depends_on:
#      - wordpress
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/:/etc/nginx/http.d/
      - ./nginx/tools:/etc/nginx/ssl/
      - /home/${USER}/simple_docker_nginx_html/public/html:/var/www/
    restart: unless-stopped

  mariadb:
    build:
      context: .
      dockerfile: mariadb/Dockerfile
      args:
        WP_DB_NAME: ${WP_DB_NAME}
        WP_DB_USER: ${WP_DB_USER}
        WP_DB_PASSWORD: ${WP_DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    container_name: mariadb
    ports:
      - "3306:3306"
    restart: always