version: '3'

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb
      
networks:
    inception:
        driver: bridge

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/:/etc/nginx/http.d/
      - ./nginx/tools:/etc/nginx/ssl/
      - wp-volume:/var/www/
    restart: always
    networks:
      - inception

  mariadb:
    build:
      context: .
      dockerfile: mariadb/Dockerfile
      args:
        WP_DB_NAME: ${WP_DB_NAME}
        WP_DB_USER: ${WP_DB_USER}
        WP_DB_PASSWORD: ${WP_DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    container_name: mariadb
    ports:
      - "3306:3306"
    restart: always
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql

  wordpress:
    build:
      context: .
      dockerfile: wordpress/Dockerfile
    environment:
      WP_DB_NAME: ${WP_DB_NAME}
      WP_DB_USER: ${WP_DB_USER}
      WP_DB_PASSWORD: ${WP_DB_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      INTRA_LOGIN: ${INTRA_LOGIN}
      WP_SITE_NAME: ${WP_SITE_NAME}
      WP_ADMIN_NAME: ${WP_ADMIN_NAME}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER_NAME: ${WP_USER_NAME}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/
